apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdbs.myapp.cloud-ninja.name
spec:
  group: myapp.cloud-ninja.name
  names:
    kind: AppDB
    listKind: AppDBList
    plural: appdbs
    singular: appdb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
