---
- hosts: all
  tasks:
  - name: Find all existing AMQ artemis resources
    k8s_info:
      kind: ActiveMQArtemis
      api_version: broker.amq.io/v2alpha2
      namespace: '{{ meta.namespace }}'
    register: amq_list

  - name: Remove an existing AMQ resource
    k8s:
      state: absent
      api_version: broker.amq.io/v2alpha2
      kind: ActiveMQArtemis
      namespace: '{{ meta.namespace }}'
      name: '{{ item }}'
    loop: 'amq_list: {{ amq_list | json_query("resources[*].metadata.name") }}'
    ignore_errors: true

  - name: Remove an existing AMQ operator subscription
    k8s:
      state: absent
      api_version: operators.coreos.com/v1alpha1
      kind: Subscription
      namespace: '{{ meta.namespace }}'
      name: amq-broker

  - name: Remove an existing AMQ Operator service version
    k8s:
      state: absent
      api_version: operators.coreos.com/v1alpha1
      namespace: '{{ meta.namespace }}'
      kind: ClusterServiceVersion
      name: amq-broker-operator.v0.13.0

  - name: Remove AMQ Operator service
    k8s:
      state: absent
      kind: Service
      api_version: v1
      name: amq-broker-operator
      namespace: '{{ meta.namespace }}'